<?php

// $Id: ext_json.module,v 1.1.2.6 2009/08/07 16:21:07 apanag Exp $

/*
 * @file
 * ext_json.module
 */

/**
 * Implementation of hook_perm().
 */
function ext_json_perm() {
  return array('access ext_json');
}

/**
 * Implementation of hook_menu()..
 */
function ext_json_menu() {
  $items['ext/json'] = array(
    'title' => 'Ext Json',
    'description' => 'Settings for Ext.',
    'page callback' => 'ext_json_json',
    'access callback' => 'user_access',
    'access arguments' => array('access ext_json'),
  );

  return $items;
}

/*
 * Implementation of hook_disable().
 */
function ext_json_disable() {
  variable_del('ext_store');
}

/*
 * Output a views object as a json object
 *
 * @param $view_name
 *    The name of the view
 *
 * @param $display_id
 *    The display_id for the view. 'default' is the default value
 */
function ext_json_json($view_name = '', $display_id = 'default') {
  //build the arguments for the view
  $args = func_get_args();
  array_shift($args); // remove $name
  if (count($args)) {
    array_shift($args); // remove $display_id
  }

  if  ($view_name == '') {
    return 'Please provide a view name';
  }
  $view = views_get_view($view_name = $view_name, 'true');
  if (is_null($view)) {
    return 'No such view';
  }
  $view->init_display();
  $view->set_display($display_id);
  //$view->set_items_per_page(20);
  $view->set_arguments($args);
  $view->pre_execute();
  $view->execute();

  $renders = array();
  $keys = array_keys($view->field);
  foreach ($view->result as $count => $row) {
    foreach ($keys as $id) {
      $renders[$count][$id] = $view->field[$id]->theme($row);
    }
  }

  $output = array();
  foreach ($renders as $key => $item) {
    $row = array();
    foreach ($item as $title => $value) {
      $row[$title] = $value;
    }
    $output[] = $row;
  }

  return drupal_json(array('totalRows' => count($output), 'rows' => $output));
  exit();
}